services:
  app:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      # dockerfile: Dockerfile
    command: npm run dev
    container_name: library-app
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:5555:5555"
    volumes:
      - ..:/app
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - db_data_library:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data_library:
